name: publish
on:
  workflow_dispatch:

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - run: npm install

      - run: npm run build

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: esneves18/yes-bank-app:${{ github.sha }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Push Docker image to Docker Hub
        if: success() && github.event_name == 'push'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push esneves18/yes-bank-app:${{ github.sha }}